# Generated by Django 5.1.3 on 2024-11-11 04:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='users_online',
            field=models.ManyToManyField(blank=True, related_name='online_in_group', to=settings.AUTH_USER_MODEL),
        ),
    ]
