# Generated by Django 5.1.3 on 2024-11-13 05:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_group_users_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_name',
            field=models.CharField(default=uuid.uuid4, max_length=40, unique=True),
        ),
    ]
